###############################################################################
#                           Common                              #
###############################################################################
[common]
   version = "0.1.0" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

[nats]
   addrs = ["nats://10.7.14.236:4222", "nats://10.7.14.26:4222"]
   topic = "vgo_metrics"

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################
[[outputs.sms]]
[[outputs.mail]]