###############################################################################
#                           Common                                            #
###############################################################################
[common]
   version = "0.0.1" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

###############################################################################
#                           Stream Config                                     #
###############################################################################
[stream]
    inputer_queue = 1000
    writer_num = 100
    disruptor_buffersize   = 65536
	disruptor_buffermask   = 65535
	disruptor_reservations = 1


###############################################################################
#                           Global Filters                                    #
###############################################################################
[global_filters]
    inputdrop = ["otherMq"]
    chaindrop = ["chaindrop","chaindrop2"]
    alarmdrop = ["alarmdrop", "alarmdrop2"]
    metric_outputdrop = ["metric_outputdrop", "metric_outputdrop2"]


###############################################################################
#                            ALARM PLUGINS                                    #
###############################################################################
# Read stream about alarm usage
#[[alarms.http]]
#[[alarms.tcp]]
#[[alarms.udp]]


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
# Read stream about input usage
[[inputs.nats]]
    addrs = ["nats://10.7.14.236:4222", "nats://10.7.14.26:4222"]
    topic = "vgo_metrics"
#[[inputs.otherMq]]
#    addrs = ["127.0.0.1:1231", "127.0.0.1:2321"]


###############################################################################
#                            METRIC_OUTPUTS PLUGINS                           #
###############################################################################
[[metric_outputs.influxdb]]
    urls = ["http://10.3.11.114:8086"]
    database = "test1"
    write_consistency = "any"
    timeout = "5s"

###############################################################################
#                            CHAINS PLUGINS                                   #
###############################################################################
#[[chains.influxdb]]

