###############################################################################
#                           Common                                            #
###############################################################################
[common]
   version = "0.0.1" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

###############################################################################
#                           Stream Config                                     #
###############################################################################
[stream]
    inputer_queue = 1000
    writer_num = 100


###############################################################################
#                           Global Filters                                    #
###############################################################################
[global_filters]
    inputdrop = ["otherMq"]
    chaindrop = ["chaindrop","chaindrop2"]
    alarmdrop = ["alarmdrop", "alarmdrop2"]
    metric_outputdrop = ["metric_outputdrop", "metric_outputdrop2"]


###############################################################################
#                            ALARM PLUGINS                                    #
###############################################################################
# Read stream about alarm usage
#[[alarms.http]]
#[[alarms.tcp]]
#[[alarms.udp]]


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
# Read stream about input usage
[[inputs.nats]]
    addrs = ["127.0.0.1:4245", "127.0.0.1:4246"]
#[[inputs.otherMq]]
#    addrs = ["127.0.0.1:1231", "127.0.0.1:2321"]


###############################################################################
#                            METRIC_OUTPUTS PLUGINS                           #
###############################################################################
[[metric_outputs.influxdb]]
    urls = ["http://localhost:8086"]
    database = "test"
    write_consistency = "any"
    timeout = "5s"
    metric_batch_size = 100

###############################################################################
#                            CHAINS PLUGINS                                   #
###############################################################################
#[[chains.influxdb]]

