###############################################################################
#                           Common                              #
###############################################################################
[common]
   version = "0.0.1" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

###############################################################################
#                            ALARM PLUGINS                                   #
###############################################################################
# Read stream about alarm usage


###############################################################################
#                            INPUT PLUGINS                                   #
###############################################################################
# Read stream about input usage
[[inputs.nats]]
    addrs = ["127.0.0.1:4245", "127.0.0.1:4246"]

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################
[[outputs.influxdb]]

